name: Run test

on: 
    pull_request:
        branches: [main]

jobs:
    run-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [0, 1, 2, 3]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - run: git config --global user.email "cicd@example.com" && git config --global user.name "Your Name"
            - run: npm install
            - run: npm test
              env:
                  NODES_TOTAL: 4
                  NODE_INDEX: ${{ matrix.node }}
